# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-30 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ebusiness_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=32)),
                ('exist', models.TextField(choices=[('EXIST_ACTIVE', 'EXIST_ACTIVE'), ('EXIST_DELETE', 'EXIST_DELETE')])),
                ('status', models.TextField(choices=[('STATUS_DRAFT', 'STATUS_DRAFT'), ('STATUS_CHECKING', 'STATUS_CHECKING'), ('STATUS_ONLINE', 'STATUS_ONLINE')])),
                ('website', models.CharField(max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('href', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
                ('content', models.CharField(max_length=15000)),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('publish_time', models.DateTimeField()),
                ('picurl', models.CharField(default='http://freedisk.free4inno.com/download?uuid=30d36e6a-613b-4ef9-87c3-c83020dc7049', max_length=256)),
                ('recommand_value', models.IntegerField(default=0)),
                ('keyword', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ebusiness_user',
            fields=[
                ('user_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('appname', models.CharField(max_length=32)),
                ('keywords', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
